apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: api-gateway
  namespace: ankilabs
spec:
  interval: 1h
  chart:
    spec:
      chart: k8s/apps/ankilabs/charts/ankilabs-service
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    remediation:
      retries: 2
  upgrade:
    remediation:
      retries: 2
  values:
    image:
      repository: ghcr.io/liav-hasson/ankilabs/api-gateway
      tag: "0.1.2" # {"$imagepolicy": "ankilabs:api-gateway:tag"}
      digest: "sha256:6d9b7e743e1e6b7afb0c4e85dd6a922929a9b3481a11c628471a73250a37fd3a" # {"$imagepolicy": "ankilabs:api-gateway:digest"}
    resources:
      requests:
        cpu: 20m
        memory: 96Mi
      limits:
        memory: 192Mi
