# SOPS encryption rules for quizlabs secrets
creation_rules:
  - path_regex: .*secrets\.yaml$
    # public key for encryption, safe to commit
    age: "age12t2lrvjt7r8k7sx2ef0q5wc9xj8kk3upxzr0kx3mqgya557z0uxsvna00u"
