apiVersion: v1
kind: Secret
metadata:
    name: dictionary-lookup-db
    namespace: ankilabs
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:+FVgUBYZikPcSt/LxXzSgb0b4pHw6X4QoWXEuXp2j3cOeCcy6tFu+chL92jZ4FsIrs/rlUb0ZtL7OP2+7ry+iMwOq+J7U5v5y1kSg03s84yECECBcMPDiJPKtl1/Q5E89N6uXp8sqUEm/Pvv2TITL2E5pDWhq9AjaWtceooCbH2s,iv:Nx3Q2h3YvcBoYTryrXTEQ50/YLaPGafiFe4HscHoF5U=,tag:txwvId5TZBbdTze8uGgteA==,type:str]
sops:
    age:
        - recipient: age12t2lrvjt7r8k7sx2ef0q5wc9xj8kk3upxzr0kx3mqgya557z0uxsvna00u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVGZvSlo5WDAzdjZsQ1pD
            VnhpLytPd1IyRi9CWitOSk0rNEoxS010ZUVVCkVpeWQ3M2c3TmE2a3Zab2FDZHJP
            Vkl3Q1ZqWENqekxEa3g0THF5eE8ra3MKLS0tIGdkVjhGcFpnU3BGSTh3UnI5cmE5
            ODQzcWhjNk5UbEdmNG82d2ZSeTNRMDAKme9aaeIdSrr6dkUN2nuFLxNp4ld2ms/a
            MI9fcMUhjYwgTh2C33erCP/EtbLRM3TRSeXzgqHl8uFNWuZMY9hTRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-10T13:35:24Z"
    mac: ENC[AES256_GCM,data:kwo9dRs7uVR11HfggATJRS+dlg8o8jjqyNdzdtsbVzYqTVXSv9gngAm31KviivELvj0joQvBY8DaGE96uBlOd/sXi4gbxMMW5ibI8kqW7ySrGult+nQHlM1cF62AQM/tJDFsge94dqh/rLFEzo/CVMjXardSDVU6b88y74V7CLQ=,iv:C4RDhAz4NvOXbA/Y9ZN0XE6XuDdXP5B9LwgLre1W9qM=,tag:k9IPXQIgPdUmaehvIBrq6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
