nameOverride: ""
fullnameOverride: "quiz-platform"

# gateway configuration
gateway:
  name: quiz-gateway
  className: quiz-gatewayclass
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  proxyName: quiz-proxy-config
  serviceName: envoy-gateway-proxy
  listener:
    port: 80
    protocol: HTTP
