nameOverride: ""

# gateway configuration
gateway:
  name: homelab-gateway
  className: homelab-gatewayclass
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  proxyName: homelab-proxy-config
  serviceName: envoy-gateway-proxy
  listener:
    port: 80
    protocol: HTTP
