# Encrypt with: sops -e -i k8s/quizlabs/charts/monitoring/controllers/kube-prometheus-stack/helm-secrets.yaml
# Values are passed to the chart via HelmRelease.spec.valuesFrom
apiVersion: v1
kind: Secret
metadata:
    name: grafana-helm-values
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:Q7t4UxnaohbfF4idhLeeFzP6TNwnVdJ5ZTwYrs/+261EaoisiRUODYyLhNKjArHCCFFh6JtqHoM9tRE2dEAc2/AWtoLXFqnvart6gRQ=,iv:RQJJQEEZNbnPj14ea8Za8+wtmW00/dZ0v2lQln6JVOg=,tag:+x48c1LVtL8EfEdkLkW+4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12t2lrvjt7r8k7sx2ef0q5wc9xj8kk3upxzr0kx3mqgya557z0uxsvna00u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSWs0VGp4SElaS0lsRUZO
            OGYvNmpoN2p0S3dIeC9paEVMSEV2eTFIejJ3CnpkRVZkQXgzM2dLZEtMeHd3bjhT
            bGxLUzV1YU5TV2hrQXlMSXlJVDVtZVkKLS0tIGZXSzNjVkNOYXBsTTR1UnhFcEhM
            eXducE5ZUlNTWWF0Qmc0Um1Ea29DMGcK3andqwYnJ7gmkhZwOnjimSRZrLXWpPlY
            JOxOpaTW6FpoCQ3MiDzwCBzr5pNGdjXl4bs1hZLP+H5YkBFimheHXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T17:12:25Z"
    mac: ENC[AES256_GCM,data:WIE2YTsUdS7PslRMcvFhpDcUu/BKhQlWzZPbhwFiJySOAwExSc81DctkVGFZ+rQMu32fRcbLiQJ4rrEFhjRPbLCCR/6SuFJljVUjVoYeRA+BrVqnPCu6BF5BtP0sOuU5wQHUmPq2sZPaDRZwAWostPpo1KjXE1fgButn+MAMpXs=,iv:Jf5YZykuWHRXhNxdTcUTOZPkh6fr4vC9C+38RMqG8N8=,tag:xhtVGivlW5A6mCWVE0oYUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
