# Encrypt with: sops -e -i k8s/quizlabs/charts/cloudflare/helm-secrets.yaml
# Values are passed to the chart via HelmRelease.spec.valuesFrom
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-helm-values
    namespace: cloudflare
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:HFH5yswJyqS6fGbcx19GjsTnMKM5mRo1OIhPXzKnI/7rFQx0bmeTZo/lRqPAhNfHnl3ZyJgbLlLWbHKt0zLKt9reWQ9nWmHQrA9pjD/Wtg9jAuS+38i3L0f5AizT1gi2jK0PyQUNx2F/AS3CFenf8Da5pkykIiqiZiL2zQjcCmIXaYcuDYlYfX5/2Oo+G7VFQvaIvhplLZK7sL6RbY0J3pGE5YgjSKuM7P2a13lEiB2k8rNH0cV5oSZF5A==,iv:YgxXZQ6t9B+DHsjNgjteFLPKY/OQ6w63YyKOEH+5VQM=,tag:KdJzcI5Ljbw3Siw6VTUR0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12t2lrvjt7r8k7sx2ef0q5wc9xj8kk3upxzr0kx3mqgya557z0uxsvna00u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZjFvRy9TTG93U3ZUM3pX
            Y0NkZ1dHR3k1WExNazhBNExqSGJPa2lXMlNjCnczMmM3aWsycnlSdEM2U2pDTEtQ
            V3FOeUZxeGRNL3FMNlAyczU3MnEwemcKLS0tIDgxVEpmc1RjYXRlTHNoQkVaOFZZ
            NG9OVWNrUjBUUUh6MWJENC8zYTE1Q1EKX1q4q2cc2Y4ek/Y3gwvK5sLHDBW348Ci
            gaSadGghZxwqKSK26i3RMIQmWsaVOD+qoqqz/QwpUrbRqwr2svW+xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T21:36:25Z"
    mac: ENC[AES256_GCM,data:itSZtbfr5u3Ufk+k9aqSYBaW3EZ0DaCcR0BHYGcYEplOEgJUpL0vWlFoEkPtLXahKnvMEJisdZpVNmwKMROO4N7PqPLmjwtP1qZ/GbwOU5eyhJyR+FMbOQwIYJeDY2J3Kum6pLeQXshzHpOs80h76kFXYzx72ivnWGS4aqCyRHI=,iv:zuujSVDNjbOMjYRdglXr59SPx8isWK1uNSjyh6kfUTE=,tag:CCAfpBcVd7ZepxwYnGmDRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
