apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
    namespace: ankilabs
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:+oEOqPpBXFRoWvjR7yCO2kMU308qrMtTV4VhVw8D8MG/KPzzaPM875/+Cl/Nxt+BWJNpL29/tYFuq2XV3JgBWKliPY5ilUDYltgIcS7sb5QtVHcTBqEQTEkj7jN5EP151sFvujBMWk80,iv:gPDC/WHsYv17koAAFO/jNfTUl492eBUj2lv1i07itYY=,tag:nqLot/43Ewrb9Em7PcF+6A==,type:str]
sops:
    age:
        - recipient: age12t2lrvjt7r8k7sx2ef0q5wc9xj8kk3upxzr0kx3mqgya557z0uxsvna00u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWS9VbThISkpRU2ZabUZH
            RW5zci96bHp1OEFncHdYNGQ5TzJ5RWQ5bHljClZpN3VJRFZOTjBvaUJObHZkWWNs
            MzB3Wm5GeXJpVWFhZEFkbFQzeXFlSXcKLS0tIEdmR3UxODdyS2RnRnpTZmVrZDM1
            cnIwNVdpbFVpeGVTWWFET2RSdGtXZW8KDp/MeV7wffZQZkSM9bmcmT4tz7alUciB
            3L+AJgPVwOrmrkauSgXkgmF47T5fakMPzSz5VhhmMa6XDkajaIPVAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-08T18:09:10Z"
    mac: ENC[AES256_GCM,data:n4BnixKSG2isbxYNSJ2RJumwjbw52CylUdLg3R99MFSFmEe0HcaF/NOUTJcCxJoyf7Plj2+qqw4yG85Ds3Orp0ImOaz+fYaEnXe2OYxpno3xjX1Zm/TePCTl0IBnCVEqxgp0WCY8jD0FTgsbCoiCVjbm31AO0WkGFCQ+TrJtt10=,iv:vo4ov1CkU6DVq3EAbq0np5YvgGhmr9JLITxx+zQJxXI=,tag:JzgkcR4NmdsNoby21KDKkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
