apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - notifications/
  - ghcr-pull-secrets.yaml
  - image-update-automation.yaml
  - httproute.yaml
  - postgres/
  - dictionary-lookup/
  - sentence-lookup/
  - api-gateway/
