# Encrypt with: sops -e -i k8s/quizlabs/charts/workloads/quiz-multiplayer/helm-secrets.yaml
# Values are passed to the chart via HelmRelease.spec.valuesFrom
apiVersion: v1
kind: Secret
metadata:
    name: quiz-multiplayer-helm-values
    namespace: quiz-multiplayer
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:phitTGbmxY2Oiy7Ica2rbmCDfm+SkI+vZkcF1Vw0b2C+7p2JurEN6uWDkCEoOM0cHMloUPWGRt7fmlsH3v4XwHKb1HBzwg4a/fyN4I5+IOOmhVfkSx3wUttEfdaWiOxIL707vBFoZ+icZ9rMnFfCzsHilXCqwuWjOmikkHdjhIRLXGndGluDpim8JFTP,iv:HlbJzG2Q/biEDEP70UzK/aIOfyXlWJGcVlbXRrPKZTM=,tag:CeIKNpjD7+yfC711X/jXRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12t2lrvjt7r8k7sx2ef0q5wc9xj8kk3upxzr0kx3mqgya557z0uxsvna00u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDK1RJQktNb3podnV3SUhU
            UklzRHcweHZwQU5DRWNmMU8wTWlpY1c5NVg4CjNVeVY3MlpFYlRRU2syaGNQRVVn
            UnFlb0dXZXhRYXlQb3haQm1WSUhFcjAKLS0tIHpkSDVxWll0eE1udHg4ak5JSE1P
            ejJqa3FEdXcrU3J1cnpsSXVsSXdnY1UKEnqHYeZEGQWRPAtw/IJhcN109eOrAiAR
            tEppvXYx2VHXmjFQsc5mcRCnw7fYsdRZnM/4YCy6w72zX3hEGltPUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T21:36:26Z"
    mac: ENC[AES256_GCM,data:0iDhCOAxJ4zuJbOxi7trSd7X3onUHG6N7V/yOQBaJzJuJo5DFWF8z1Fxip+216LeUNrmFQYV9tVW0q1spKa3zsCphAdHg4CoKvpf7Hv2t8vZOLEPjM4Id3UdigG3Q4vbgNrvA3ljHdIoPob2tVQhxzvmvOlB6zCDWug3wF1PMls=,iv:FjASEZQPEUmXXa4KUgts76lZLPmtTkWdCRJUuIliDU0=,tag:dyOMs3I3gqhPzmVV1gq7+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
