apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secrets
    namespace: ankilabs
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:EuotGbELpGxv0366xsRyCz1D+26iXj5mzqYBl1aYfu4NEJsp5HTT3yE6Aa2MGcOqW3o954eV4c0lcaHhbq+NF208TuFB12ZvDQWXB+WxEmyQRWVyzIa8480RBUVG3MPifcSY/EuJni8IT1y79DHrETLM1pEHIFmY9Sw08g==,iv:6m5O0O7oMEBjfPsNU5QRVEyWvAP8a4iqJnllGgKV/TQ=,tag:6mDeKFUNI8M+iN8c/xMEaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12t2lrvjt7r8k7sx2ef0q5wc9xj8kk3upxzr0kx3mqgya557z0uxsvna00u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRnRoZ2Q5OE5hUWFNM3RT
            Tk5zYWo5N0Q3eGp0NExzOWZvZTdoaHFwUzJvCmxnSVhTNXpkcGhlZUlnc3N3V1RI
            NjhMQ3hlU1gwbkhRV1hiNG9udHJNSDQKLS0tIGRXdmplM1FYbCtpNDRtT21KQloy
            VzZuRUdKdWRRbXBHQ1NhaWlpT3dCYncK41PMFSvMHw7la55iVNbdoFkid7etW5xI
            TpTMuVz/0zG6kTIE5ULdpXJojpkB4U2kWSr9RqqfktJFF5LXu8zOrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-07T20:40:30Z"
    mac: ENC[AES256_GCM,data:0y24KSk8INTUnIvT3US4rp9KSavI9DjKhYnSIzLfDahYw9JYV2ew4wdEVJkCAyPeFD8NK7Y8yGwNkNcHREIqWLY/QUxms8es7aNh3E44R3UDOQxyliT1p0DSsldkS7HzIzneX3Zx//2+LACFYqGmHwYl6w90z9ku9QPhETSp2Z4=,iv:/7dvnV/BN35dVOHETVpQMJtF/9wKJwhvukwEvfx7Vbs=,tag:X8rhaGr1BWwsP5L2WW6HzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
