apiVersion: ENC[AES256_GCM,data:Yaw=,iv:rVAEu1YUXfJKAqrS0qYcGOjyDMacKc/POBa88hot/5M=,tag:ctX/flCJhI3AIStUOMK+8g==,type:str]
kind: ENC[AES256_GCM,data:P+s/j4pC,iv:FlxNepdCP1lNLwpcAqBHrZmEWzx5TFoSihuoVN0gINg=,tag:0KASYNYabhZAOkcHGS5ztQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:OqItMZ4JW5MDnAbzKjPX0dK/1ScEQ3E=,iv:X0fmZz+oq8oCgxLI+FaHIWp4lyCaZ8pJrRmfX5kvgeY=,tag:nEbtd0RBjRfbWhzBDd9DCQ==,type:str]
    namespace: ENC[AES256_GCM,data:ZJhdqorv26k=,iv:G/A1JVScdfTsvCgTUtPPhFZKy5djdTbLTuIpXfOrhXM=,tag:gdk4qx4EmqswLR5WAT/e5w==,type:str]
type: ENC[AES256_GCM,data:gHDr2qRs,iv:yrAMlSkvyT0GYSYStxTios3grWj53UBT0CDJ7uaNMXQ=,tag:aYRtveF6aDHDDaosu1UZMQ==,type:str]
stringData:
    address: ENC[AES256_GCM,data:nADHGgE+htJ5+8AUCq/XvUTc/IRAfwskn69lJgOsB7bvxWS7HQ+pYm+8a2xYGZdnI3+mBX8Ra3xADPXZDOTzWzUNQo08ceyGyYS1ttqS95PbCtKa4Z2oiJu3JoIWTiQQA3Zd8XSjp1BvAlvA7w3GECr0OWCdZcDMnINDJQ==,iv:VUDKUVGSioP5gclDeBnm9i1zPNRDLJd1olIRGsOMEZ4=,tag:J2IuRsa+YGsLwtllL9MIVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12t2lrvjt7r8k7sx2ef0q5wc9xj8kk3upxzr0kx3mqgya557z0uxsvna00u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSHU3aDFhb1B1Ymdab3Zo
            MTI2SlJzZDl4dmFGam9yUWo5ZTkvVStnTUc4Ck01cnJxVWZCZE5heDBGU2xocHdj
            ZCtTb1dOMDF3TXJPbmNxNFplMG9CTTgKLS0tIHZPL0Mrand2Wll3MEt2VEJyUXpJ
            dUhOZEFhOTc4Zk14NVMyc1UwUU9UU1EKXwmYoi8fKnq7+c/xbD/y+cCfBebua2en
            AQumxwk0JrOB7yDvg7HlimkJWTytajnRdY0cHzR4NrzgLGErC4stYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-03T14:45:25Z"
    mac: ENC[AES256_GCM,data:emXgQ+4xQcv6QDKz4QiyOW9lw+k3Fe5JdSONps/zONX1CFtwvJyWZJLOFaIiHcF4AN5T/ayMkR2cwulU6Q83P1GQj4Zb9d9Ff/gNji2UgWk1lQae4Mkq+nPlapwgnOSB2vau7izsyDx7Eg6y3vu/Ut6bKJxrvkR1LDVPF6f21ik=,iv:5RWpvztSVHnPiaH2UJ+xqP10RbztVQ+8xNuB+dnw34A=,tag:okk/f/jkcISsMtLtH3D2/A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
