apiVersion: v1
kind: Secret
metadata:
    name: sentence-lookup-db
    namespace: ankilabs
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:lIMlPtbtxFzysP0I8H6a8jEvST6NcFUahiallv0B8VNdJT0RdQw/fyL/+zQ5gaggC4y3m1jaxkqSBL3q4msFn11h/igVnTslCUvF8FRjgSSPLgNcouVcnx6pXniLJs3MvULi53e8+kk6QcCVGBbGsWRBp90Pvwof5XCooNzuwQ==,iv:2H0vUZ2CCu1urK9ukpK565XFr4/CcPTM8V2aZChQviA=,tag:Q7pMmXabXf1zCepRZwYCyQ==,type:str]
sops:
    age:
        - recipient: age12t2lrvjt7r8k7sx2ef0q5wc9xj8kk3upxzr0kx3mqgya557z0uxsvna00u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbkVTemtYc3l4YXZwSlh3
            VjFWR3plamozL2tLTXlrLzdoRGNRK2FjVDNvCmIzNzZoSjd1dHB0REVVbmhRWlI5
            VHR4cDZmcmhIV3R0cTYxN0Q4M2hadDQKLS0tIEtYYXdmOVRmeGg2WkcyTnpzNVd6
            eDBOelc4bUcrYlFvemQ1emJrTkp3bXcKm2vfn1FF8rDJCqKIz4L4I68Mi6l8ijn9
            K09eFu/YqfQyKjPCL8ufq1GrBxwX8f9IRFe7PMRmNclMYa5Bzuujjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-10T13:35:24Z"
    mac: ENC[AES256_GCM,data:VnVjE4MNuxsfMR5OHU6EzR4mPrjhGT2rW0pNSmjPaIOAVTsMngruyDm+VMXi2t4H9rXb3zY61NfjeiSJZcybmCC8HXBvy8E6hoPKNaUQTDOj+Gyux3ZwZr/VijxWX+CxyBEMgEh2S7oeFtKVKXKEaXiWDgttNTw2anWGsFh9DYY=,iv:own6hD8WMigsewg+7icWr7pWpFvKUQPjcJqT0h9BkAQ=,tag:GipCUR6Q9TTpUDTLZUO1sQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
