apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-helm-values
    namespace: cloudflare
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:Q3YBYjM/pKBHxJzVFFlt7A9OnCU8DCYAetj79YRG0kWBUlQDaft0OThQh+jDWbTv8sB6iu9aWfSwUoilLcDjg9qEALFJhEMVKGhDypRP9NOzJzBjhFJFDu0tNcxn8UhXGowQPdd8rkvCkeTM5kk4owc5g3Wu8sN3xxV3e2v2klJcp9SBMIPFUSpiMZQnSWEUQUCjZJ1Alpt27EM7ymzonPjIDLjP2CAQE395ze7DskIeUZ1a8YgklxEn4H8t+wlDGr/mc/eEWAvsuABUjwhLscq6K0kxrGRK/8ol59iBP++/RCvbb2E7TXa9tpWg/x6j2ORKIhmyM5jX/9+N46kXU9B21XkACtuAX0i05botnvQ116BRkpq4tbsj6kCVKYcrFhTdtCiewX43IMXGofpXVbCrHQIcKevUSxjGhFDMNorneDLTbIDl6IFatu30i36OfE1TkvzKZcg9IEEJbBFyr73sEjiDpng1MNBQE8Z7Y2ful2H2gxtV7N/fQcstF9wcsV16rdNIw4xUR/7nkyKfTjePtkTfoWLGeJSNP6gAjhQcA06zs5YoGkm/0oizdPJ/8xOoAdlkF2BXSZL5TXXkyg7qqmwOY6r85iR4+RLhgrREQqiK3HnbKc9R4D7d/IKArz1yFzaPyoAayqOmcEzxuz01uuJqpMHX0RxQ1i/2PbX1f0lRrHRKY3eFboAcucauVG+XXetK26yrKFc5s4RuGCjhdMD3wS5xCjRibK8ceq3iDTRYKtcIikXQwn1KPEeEr1w4BjoF69FOpMgySEWCpjl5kEeldMPiXL7GAxspFkbvZxYMf8RNnHQw7TEZtRBmFemf7maG49yDoFv+aKRdnWPs8FMLyMtdiy1Fjciqefk=,iv:BX9aohetXBzPz8HHLb7UACPD/4SZMLeqAy53HY78qpA=,tag:V2TAo98DebJFuNBVq8dr/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12t2lrvjt7r8k7sx2ef0q5wc9xj8kk3upxzr0kx3mqgya557z0uxsvna00u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdGcrMmFBS2U1QVNwb2tm
            M29Yb25wbEtiVmZRSjVONXBsME90dndBbnhZCi8wcUloZ2o1cE5rL2tKUVMrTjNH
            aTJBdUJIZlZiVWxxZERjbldZMFZseWMKLS0tIFdKekRsOE5GR0wxZ0RPWTJiS3BN
            aDNOdGJsdm1LQ1lpVWFvSUN2THpsU0UKRBBArPP9PqoT+6PcH8qc6s9J3tcRT6I+
            aSK6lzZW3FtLttYHk53eSqwpEPKpaolkI+Co2xmM9OrGm8M19XwvHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-07T20:44:49Z"
    mac: ENC[AES256_GCM,data:DuLjoORp5H7d5k6VAwHwf5GLbOCB08AYY1DtMozTkyRFbxQn+z/lJWcOY02KE0xqYoJtX5WwPOZb8MVspZKP1U43ZFp8GEi8XglKAEAFD7baWgCd4vRBN6ub0cVV7tiybaIWuJaKRqGmLNddiBNq23WXHiEi3fCPi39KMKu/qAg=,iv:qPSTZxEEhSgvvvTezIfQ+UMFxwZcoCSF47f8K7Ung0U=,tag:9Ggyrd02mVgAW1lC7F4SKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
