apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
    namespace: ankilabs
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:6vlCc70Qjz6+tHJI4L1oM42zngZ4foglN/lFDJWcVD2xU4l4rISGTIr5xd2S8ha5,iv:be6hriHml8oTMruC4AsT9pGQ7Cp4l3Tviq8eCLlGxsk=,tag:3Sx3maGxcuWxKMoL+56XVQ==,type:str]
    DICTIONARY_READER_PASSWORD: ENC[AES256_GCM,data:g9GnAckUggdIwQu+YpTdzeyq2n9cFps5LuiliL71GYMWAZKs4Q2j//+afiYgd/qu,iv:+14/Bu9lRlXqatB8DqwLOlhwonEQR0H0/7wpD+h78mo=,tag:1CEKKld8nNvc0aSjTRYlRg==,type:str]
    SENTENCE_READER_PASSWORD: ENC[AES256_GCM,data:AdbMjIIULdDC743oUTABIcY+Kl6WS1bXGCiOD5jE9MVrK+4Tn+BFntlfvfbTLJJQ,iv:a3yxGslFqJRcQki2lgfVKc46jg3hPapvtO3TYVLoCtU=,tag:+ki46APm1mfO+KqX765SoQ==,type:str]
sops:
    age:
        - recipient: age12t2lrvjt7r8k7sx2ef0q5wc9xj8kk3upxzr0kx3mqgya557z0uxsvna00u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYm0vc3NiSzc2cThLS3lG
            RXAzU2RSVlJJTTd5SkFSV205N2F3V0lpd0ZJCmdTT3Rha010K0VRc0ZmcmpyejJK
            VjlrZSs5NUlObGRIZmdPTGRTL1lPMU0KLS0tIGhDZUN4SXI3anFUV05OSTUydnVH
            VDNwQU5mOFdQYjRERjZoTGpOV2JrTFEK1hpUzrDuJHF8xRuLv+XzW3mcnLq1vGHT
            RKFv3IVHH1GKzXPnK+PIgviZderGJTM74oGbD/xDZGpKwx3U83DLpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-10T13:35:24Z"
    mac: ENC[AES256_GCM,data:1mcQddSMfZXyiSi9Q8VlisXd+7qvXlzt7h97/l4OaQaw/P7gybmhMnESpRPKXAauF8LlOvjsGWVkbFlttEFpB/GRY35KkQdCQ1vHQHa8hAcKnjWBgI8vBf+F0i6G8UlTDYlt/j5YWdJ3Ju6UwAhazrsEdBD6wHtsGjeRkuN9+VQ=,iv:wZSjmz9hzQPFWA1LRpyzUKR2VbsPha9F6krvOC3IZ9M=,tag:J+L0OVFaIuLZYSSg4l/VYA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
