apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secrets
    namespace: quizlabs
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:9ukk4W7pXjrkN5x+fKXyKJ0E3uxlJpGm1VXq+agu2VQuFX0oH4mRc6F6deRAj8iiHno+cjVwNQh8nCkLZmVlPsOMDz7zKsMz3fXH/PtOn2a6rsi5FjQCufwpqphyrbTf6YOv314t0ueCvb6pU1UUoVfQ8WWjVEZhdOC9MA==,iv:4NFmHPRQIpXQcNz8RVXmjSrcO1Mi9djHebrIn8IjvzM=,tag:y0PPZSXqb2xOu7JqkY/44Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12t2lrvjt7r8k7sx2ef0q5wc9xj8kk3upxzr0kx3mqgya557z0uxsvna00u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUEE5OWU1V0ovdXBiZVJS
            aVVMQmJrQVZ4dUI4QllPKzRXYjR4STg0REI4ClRMMTVET1ZQay9BUk5zU09iT1Yv
            QWJqclljTzk4Q0FRUWtTdjJvb3VMRHMKLS0tIEZOYU82ZGpKclRxWDZjS1ZEYmNz
            N2tyRW1FWktYcTRmMGRLaTExNk12c00KjGWzO1PbSl36tKKOZa6qjDvCKTy8vjon
            08QVtk10Jac/wrITmGaPgpPJq+QkYjoJUovcuH0jDbe0VomYEXokvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-07T20:40:30Z"
    mac: ENC[AES256_GCM,data:DKNKVqULUwRho5pUdJwCs/zBW/EonBmaNOM4B+BzrbI4SVtNrNDzCvwlhlh4H8Xwb8c75MLHeMt9hfxSq2lVdlKexZXqmEPV9q/PdXFVAKyOAtyNJ/55fLagCtY2CxRgx+sMtdzuXpWbh0diuWOHQnRvsCU0m/jKeyUsWzF81l0=,iv:gPC2vxWPKZQeba11K29G8GbIIJzHv0jcTddO/Ko8j1g=,tag:vnkE7Y9zLBWawDhDfZmXaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
