apiVersion: ENC[AES256_GCM,data:4mo=,iv:5eh13QpgjXogjQJtev40OEtCgULwaLB9QmsgYTjBosQ=,tag:IgKr9mX9v153mYI6f7aQzA==,type:str]
kind: ENC[AES256_GCM,data:um3gccmI,iv:ePC2NxgK4QQowdHmRiEvClpHpSEhzG5mjQp+gBSa/AI=,tag:JzzvaLKs8xmBzjAUReeQdQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Iwbmwlv+k+drIF/i34uSmKaDX2o/9tQ=,iv:G8oeo6kyu1mPPmMkJ1uJnnHFisZs7bO/cRQVczeXTmk=,tag:lt0nXkwsbMqiAjrvis8kdw==,type:str]
    namespace: ENC[AES256_GCM,data:R95s/eI//XQ=,iv:UA732gXTSLBsCtWtMU9FVxxbnqx17kv96x9WV6zS0EM=,tag:c0q3TLaDExsYHcbpP4nIrQ==,type:str]
type: ENC[AES256_GCM,data:hvzeO2ff,iv:s8keqicEMHaJO7Ur9htpmIke7wdn0Gqxo4XnwG+6194=,tag:Hc0TxVx+OF2ElbubsNjWqw==,type:str]
stringData:
    address: ENC[AES256_GCM,data:bJzpq7Q29LSlxd96ivLrPhGYYcHiaoSiGb7rKblzyW+X14lY4VPP2Ky0avXH9szcTW5ZdFN0QtwsbA0naMmY/weN4Tlzqa8fZLwL2MtqRELK7Q6Gg44FCDyjgobE41aiub0umxtGtlEbMRcrqMR3V80LvByHJjQsBvkhLg==,iv:T2QPsNv6417CfKf2H/Em++8L0J+UmF8CjFbjwokYhXM=,tag:VKWbfZajZxXNRxvRcPThnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12t2lrvjt7r8k7sx2ef0q5wc9xj8kk3upxzr0kx3mqgya557z0uxsvna00u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcW1mNTM4YldtMUdpem9l
            OTRrMWFYVG5ZUXVVcFJQMnF0SnJJUlFKdkJFCmMrcitCU0N5YkVnaGl6ZCs1Z2Nl
            ZkxxL3VONDBSS3NQNVByT0VTK3VMWkEKLS0tIERLT0dTVjduWkRHVEl3a0J2Tk5T
            bTdGYnFFOTk3Q1M3VmREams2WHdLUmsKDG6PSzFNwRgC/WnQXlrqJTFSee515sZ7
            KWOUaayZb9sknrpKPF4q3wnk6WEoRirm9XtwC+9GlzSmbk1txxicGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-03T14:45:55Z"
    mac: ENC[AES256_GCM,data:uZq8QkRzFB7F7+Wjbv5+opj3j4H/R8OdsMyWV6niozgm4gJ9bLO6hJdKBxtfqzJNfoN1+JGVxHPjdNFB3WmnF6OVQlBBUUw5ROCplAIYZZ6f+YjHrfgWikfkiu+isE4k7aryy7d2+fgvS0WwgdgJ9cy7K1cFmusz3etjR/N9ykU=,iv:QWk7heXcqrkIUZE3XoMNJnc2rNYKd/GwT3AajpcAd0U=,tag:tYZOIZKHRYv1AlXGn3Rp+w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
