# Encrypt with: sops -e -i k8s/quizlabs/charts/workloads/quiz-backend/helm-secrets.yaml
# Values are passed to the chart via HelmRelease.spec.valuesFrom
apiVersion: v1
kind: Secret
metadata:
    name: quiz-backend-helm-values
    namespace: quiz-backend
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:IsdNTK32ebJknZBaSskZmx/1l9dj/y9DDij3gXoyfuTeXPWtlD8q+lMsHMGtUNCUfIAHrrL76uCKWWYnuyW8dF1vZ8hqxRQyUHn87L/m7vi0Ib8td0Ralpx0PVQZ8F8d8gjZk0hgLRrlrWNt2wjrHG2lplH77z8pRKc+nY7EVnS+JVYNhFoxqxmo9ilMCmRArSV00wdR9oU03Ml9y7CRGaZa4ar+L/OAgx1HHsT0Ct5EeWf+22IQ9OI6LYiLiO94XE4LcHwGy1OLVljlTmAMObsbBagdCthz5Se30zvDvCjlHapcAEn2QS2og2EErP2VP2fp4gS6sDEOfY7F93Ci6l2D7lSDk5eWnXINjuTgtxDIJOx0tIKShDHU4IM74aM4YCI2QouL8CUJUaI0i9gDgLJOyJ2CNrUSbuFDSwGOJ0uCjI4VOmEr2mLarwIWojQ/+5KOVB/v/0t6U1w6Knqv/2wesNaQN83Z0dXmxMLFAs7+HvmbcWJ/eYMGtjnkKyo=,iv:DaS8VWuvH/jQuE3kG6IvlC2WtTnMQEiDkr4mc8xd3Tc=,tag:/zxHvD9c2xDqhDHNN6OAJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12t2lrvjt7r8k7sx2ef0q5wc9xj8kk3upxzr0kx3mqgya557z0uxsvna00u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWHZIaFRwbytVd3FsMFky
            WjhXYzZXd1RpcFViVjIyTFNGamM4SDBxcXpFCnJBRHVVeDErbGZmRmxTN2ozNHdu
            N3hCTDdzS28yT2RFVGdLN2NPUkRsTk0KLS0tIEVta0o2ek9abUdHVkZUNysvcEs2
            MkJoTlB0VytlczlWU01DRzlWQzRTNTgKPAz2OeElIPrTVZ6JDm0ofVFJ0JuRBStx
            tQS89MLZW6ikEAeQJlqjKQVSi2NU4GFdU9uSmTb+7E2tgXeOeZ3TXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T21:36:26Z"
    mac: ENC[AES256_GCM,data:+KPZ655xeap0dVBxePdAGvbebO5XHs5qbiCWxYA19gLvPXbaXF+2flg2mwkqMs6kxieUfPSICEUStq9Bgq6rJyoP5GzcTw+u2dYDDEY9JDlxOoUFu7l/BXXaKznf5XK646OmEcxUADNcT4o+F3cB/1mkfvOSNGIRGIcoUbgN9aw=,iv:y/TNAEHCbbQSJJ7Qu7aVGsZaOgseMbF5QjzYgup+m/E=,tag:gFTS5r1rm/uScTne0nywjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
