# Encrypt with: sops -e -i k8s/quizlabs/charts/stateful/mongodb/helm-secrets.yaml
# Values are passed to the chart via HelmRelease.spec.valuesFrom
apiVersion: v1
kind: Secret
metadata:
    name: mongodb-helm-values
    namespace: mongodb
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:ySh/l7W4i13VfL92n9K6kN3TUBBLWS6LkjE1MPhwlUhakRGsFIUpAplTQNru/MghzHQY+VsYNMgGTNMZWpAOeg8hmQ9n9UtYyQ==,iv:h7zv/ECFc+hXCQ43/R2RVSfw6oy5FMOnAhIvHrCFcRQ=,tag:pmZlXS3VWti46MVab4q10w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12t2lrvjt7r8k7sx2ef0q5wc9xj8kk3upxzr0kx3mqgya557z0uxsvna00u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TDFLQ3RkVjhQc204M0pm
            WWExWjJuQ2cvOHJ0bG9WRFRNYTJ5WWVpWVF3CnorbEhpTS85M3FNd2RpZ0hSUUZn
            N0FrazFYdGRhVTNqd3lGcURodlZCc1UKLS0tICsrZEZEM0twSnkzVDlqYlJsMHA0
            UHpxQk9zdDF1eUVVV2sySmg2L3J5K2cKFpyD/sxUu4+AiFnXmHmAbn/7Ee/hao5s
            MLkSe18u3Q2qTXFx2L8yeF47j203eHGAUEIVL16Fy9DvaAxkv83/pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T21:36:26Z"
    mac: ENC[AES256_GCM,data:YFssFCDPWAE2/GL8EP3MnEfcvLrOyGtB466UMbR+Q3IR8xFt/jHsWq13kURdc7yZMYuhAPApmecqpMJWuR1I9thRQa1GOIzvRfRt5PWCQwEkB7sFuQ5kD9GXLD0fHkd4OgUzpTrtbvlwsD/zzNuinZhJmS9Ai+ecrB5mDSHNRrQ=,iv:fybVC6kuSTJuW0lYvnhOKr4CYvEUGyjmmnIl2q8O81Y=,tag:6EqAItz4IXNTkzZuJpFwAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
