apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - monitoring/controllers/kube-prometheus-stack
  - monitoring/controllers/loki-stack
  - envoy/release.yaml
  - cloudflare/helm-secrets.yaml
  - cloudflare/release.yaml
