apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - httproute.yaml
  - stateful/mongodb/helm-secrets.yaml
  - stateful/mongodb/release.yaml
  - stateful/mongodb-init/release.yaml
  - stateful/redis/release.yaml
  - quiz-backend/helm-secrets.yaml
  - quiz-backend/release.yaml
  - quiz-multiplayer/helm-secrets.yaml
  - quiz-multiplayer/release.yaml
  - quiz-frontend/release.yaml
